### ISSUE TITLE
Does it call oauth endpoint on every single request?

### ISSUE THREAD

**Issue by andrewsav-bt** [huysentruitw/oauth2-client-handler#5]
If yes it seems... excessive.

**Comment by huysentruitw** [comment]
Are you seeing this behavior? Because a new token should only be requested in case a call returns 401. See https://github.com/huysentruitw/oauth2-client-handler/blob/master/src/OAuth2ClientHandler/OAuthHttpHandler.cs#L48

When a call returns 401, a new token is requested and the call is repeated transparently.

**Comment by AndrewSav** [comment]
Ah, all right sorry about that, I missed it. Thank you for confirming, that this should be working.

**Comment by andrewsav-bt** [comment]
@huysentruitw apologies if I make a monkey of myself repeatedly, but it appears that while `AuthorizeEndpointUrl` is defined it's never used in the code. Is this correct?

**Comment by huysentruitw** [comment]
That's correct. We would need that endpoint only for the Implicit or Authorization Code grants, which are not used by this library.

A monkey wouldn't look with that much detail to the code btw 😁
